<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-HoshiBot.Host-9456395d-60d3-4f58-b506-fba4e5f9e748</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageReference Include="NetCord.Hosting" Version="1.0.0-beta.9" />
    <PackageReference Include="NetCord.Hosting.Services" Version="1.0.0-beta.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.18.2" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HoshiBot.Discord\HoshiBot.Discord.csproj" />
    <ProjectReference Include="..\HoshiBot.Domain\HoshiBot.Domain.csproj" />
    <ProjectReference Include="..\HoshiBot.Data\HoshiBot.Data.csproj" />
  </ItemGroup>
</Project>
