// <auto-generated />
using System;
using HoshiBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HoshiBot.Data.Migrations
{
    [DbContext(typeof(HoshiBotDbContext))]
    [Migration("20260712133134_AddStfcNewsAndIncursionsRegions")]
    partial class AddStfcNewsAndIncursionsRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HoshiBot.Domain.Entities.Absence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreatedByDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("EditsAbsenceId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("SuppressNotifications")
                        .HasColumnType("boolean");

                    b.Property<int>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EditsAbsenceId");

                    b.HasIndex("GuildId", "DiscordUserId", "EndsAt");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attacker")
                        .HasColumnType("text");

                    b.Property<string>("Detail")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsTest")
                        .HasColumnType("boolean");

                    b.Property<int>("ServerLocation")
                        .HasColumnType("integer");

                    b.Property<int?>("StfcSystemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("TerminatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("TerminatedByDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TriggeredByDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("StfcSystemId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.AlertNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.ToTable("AlertNotifications");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachmentUrls")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Attribution")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("LastKnownReadCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MentionRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("TriggeredByDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.AnnouncementReadReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnnouncementId")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "DiscordUserId");

                    b.HasIndex("AnnouncementId", "GuildId", "DiscordUserId")
                        .IsUnique();

                    b.ToTable("AnnouncementReadReceipts");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.ChannelPermissionExpectation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Allow")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("Deny")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "ChannelId", "RoleId")
                        .IsUnique();

                    b.ToTable("ChannelPermissionExpectations");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.DiscordGuild", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("NicknameSyncEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DiscordGuilds");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.DiscordUser", b =>
                {
                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("DiscordUserId");

                    b.ToTable("DiscordUsers");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GlobalAdmin", b =>
                {
                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("DiscordUserId");

                    b.ToTable("GlobalAdmins");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildAdminRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscordRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "DiscordRoleId")
                        .IsUnique();

                    b.ToTable("GuildAdminRoles");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildAlertChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<decimal>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildAlertChannels");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildAlliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiplomatRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("MemberRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("OfficerRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("StfcAllianceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StfcAllianceId");

                    b.HasIndex("GuildId", "StfcAllianceId")
                        .IsUnique();

                    b.ToTable("GuildAlliances");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildEnabledFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<int>("Feature")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Feature", "Audience")
                        .IsUnique();

                    b.ToTable("GuildEnabledFeatures");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildFeatureSettingSnowflake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<int>("Feature")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Feature", "Audience", "Key");

                    b.HasIndex("GuildId", "Feature", "Audience", "Key", "Value")
                        .IsUnique();

                    b.ToTable("GuildFeatureSettingSnowflakes");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildFeatureSettingText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<int>("Feature")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Feature", "Audience", "Key")
                        .IsUnique();

                    b.ToTable("GuildFeatureSettingTexts");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildMember", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GuildId", "DiscordUserId");

                    b.HasIndex("DiscordUserId");

                    b.ToTable("GuildMembers");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("StfcServerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StfcServerId");

                    b.HasIndex("GuildId", "StfcServerId")
                        .IsUnique();

                    b.ToTable("GuildServers");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AbsencesReportMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AbsencesReportStaffMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AdminChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("AllianceBoardingChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Audiences")
                        .HasColumnType("integer");

                    b.Property<decimal?>("BetaTesterRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("BoardingRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("BotSupportChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("CommandBridgeChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("CommandBridgeMessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("CommandStaffJobsChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("CommandStaffRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("CrewsRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("DefaultChannelCategoryId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("HoshiTesterRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("LogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("MemberRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("RemindersAlliesChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("RemindersChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("RemindersServicesChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("RulesDeChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("RulesEnChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset?>("SetupCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("UserLogChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("UserNotificationsChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("WarningsRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildVeilGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("StfcVeilGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StfcVeilGroupId");

                    b.HasIndex("GuildId", "StfcVeilGroupId")
                        .IsUnique();

                    b.ToTable("GuildVeilGroups");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.IncursionsRegionDefault", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("DefaultStartTimeUtc")
                        .HasColumnType("time without time zone");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId")
                        .IsUnique();

                    b.ToTable("IncursionsRegionDefaults");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.NotificationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscordRoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Kind")
                        .IsUnique();

                    b.ToTable("NotificationRoles");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.PendingModalInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Field1")
                        .HasColumnType("text");

                    b.Property<string>("Field2")
                        .HasColumnType("text");

                    b.Property<string>("Field3")
                        .HasColumnType("text");

                    b.Property<string>("Field4")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("PendingModalInputs");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.RoeViolationReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttackerAllianceTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AttackerCommanderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ClosedByDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefenderAllianceTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefenderCommanderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ReportedByDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThreadId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("RoeViolationReports");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.ShieldReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("ShieldExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("StfcSystemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StfcSystemId");

                    b.HasIndex("GuildId", "DiscordUserId")
                        .IsUnique();

                    b.ToTable("ShieldReminders");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.ShieldReminderNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShieldReminderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShieldReminderId");

                    b.ToTable("ShieldReminderNotifications");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcAlliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("ServerId");

                    b.ToTable("StfcAlliances");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcAllianceDiplomacy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SourceAllianceId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TargetAllianceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TargetAllianceId");

                    b.HasIndex("SourceAllianceId", "TargetAllianceId")
                        .IsUnique();

                    b.ToTable("StfcAllianceDiplomacies");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcAllianceDiscordInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AllianceId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.ToTable("StfcAllianceDiscordInvites");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcAllianceNameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StfcAllianceId")
                        .HasColumnType("integer");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("StfcAllianceId");

                    b.ToTable("StfcAllianceNameHistories");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcEventDateConfirmation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("StfcNewsPostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StfcNewsPostId", "DiscordUserId")
                        .IsUnique();

                    b.ToTable("StfcEventDateConfirmations");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcEventStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EventEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("EventStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NotifiedEventStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("EventGroup", "RegionId")
                        .IsUnique();

                    b.ToTable("StfcEventStatuses");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcNewsPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LastDisplayedConfirmationCount")
                        .HasColumnType("integer");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequiredConfirmations")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SubmittedByDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateOnly?>("SubmittedDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("Link")
                        .IsUnique();

                    b.ToTable("StfcNewsPosts");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcNewsPostGuildMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("EligibleMemberCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("StfcNewsPostId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StfcNewsPostId", "GuildId")
                        .IsUnique();

                    b.ToTable("StfcNewsPostGuildMessages");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcNewsSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("IncursionsEventDurationHours")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredConfirmationPercentage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StfcNewsSettings");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AllianceId")
                        .HasColumnType("integer");

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OpsLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("ServerId");

                    b.ToTable("StfcPlayers");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcPlayerNameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StfcPlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StfcPlayerId");

                    b.ToTable("StfcPlayerNameHistories");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcRegion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StfcRegions");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcServer", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int?>("VeilGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("VeilGroupId", "Name")
                        .IsUnique();

                    b.ToTable("StfcServers");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcServerDiscordInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("StfcServerDiscordInvites");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcServerStatus", b =>
                {
                    b.Property<int>("StfcServerId")
                        .HasColumnType("integer");

                    b.Property<string>("Maintenance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NotifiedMaintenance")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("NotifiedStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StfcServerId");

                    b.ToTable("StfcServerStatuses");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasStationHousing")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<int?>("TerritoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("TerritoryId");

                    b.ToTable("StfcSystems");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcTerritory", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("CaptureTimeUtc")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.Property<int?>("Weekday")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StfcTerritories");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcTerritoryNeighbour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NeighbourTerritoryId")
                        .HasColumnType("integer");

                    b.Property<int>("TerritoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NeighbourTerritoryId");

                    b.HasIndex("TerritoryId", "NeighbourTerritoryId")
                        .IsUnique();

                    b.ToTable("StfcTerritoryNeighbours");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcTerritoryOwnership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AllianceId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastCapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.Property<int>("TerritoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.HasIndex("ServerId");

                    b.HasIndex("TerritoryId", "ServerId");

                    b.ToTable("StfcTerritoryOwnerships");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcVeilGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId", "Name")
                        .IsUnique();

                    b.ToTable("StfcVeilGroups");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcVeilGroupDiscordInvite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("VeilGroupId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VeilGroupId");

                    b.ToTable("StfcVeilGroupDiscordInvites");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.ThreadRemovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RequestedByDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ThreadId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("RequestedAt");

                    b.ToTable("ThreadRemovalRequests");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ClosedByDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("OpenedByDiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("ThreadId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.TrustedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("TrustedUsers");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.UserPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscordUserId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("StfcPlayerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StfcPlayerId");

                    b.HasIndex("DiscordUserId", "StfcPlayerId")
                        .IsUnique();

                    b.ToTable("UserPlayers");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.Absence", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.Absence", "EditsAbsence")
                        .WithMany()
                        .HasForeignKey("EditsAbsenceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HoshiBot.Domain.Entities.GuildMember", "GuildMember")
                        .WithMany()
                        .HasForeignKey("GuildId", "DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EditsAbsence");

                    b.Navigation("GuildMember");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.Alert", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.StfcSystem", "StfcSystem")
                        .WithMany()
                        .HasForeignKey("StfcSystemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Guild");

                    b.Navigation("StfcSystem");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.AlertNotification", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.Alert", "Alert")
                        .WithMany("Notifications")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.Announcement", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.AnnouncementReadReceipt", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.Announcement", "Announcement")
                        .WithMany("ReadReceipts")
                        .HasForeignKey("AnnouncementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.GuildMember", "GuildMember")
                        .WithMany()
                        .HasForeignKey("GuildId", "DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Announcement");

                    b.Navigation("GuildMember");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.ChannelPermissionExpectation", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("ChannelPermissionExpectations")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildAdminRole", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("AdminRoles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildAlertChannel", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildAlliance", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("AllianceLinks")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.StfcAlliance", "StfcAlliance")
                        .WithMany()
                        .HasForeignKey("StfcAllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("StfcAlliance");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildEnabledFeature", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildFeatureSettingSnowflake", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildFeatureSettingText", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildMember", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordUser", "User")
                        .WithMany("GuildMemberships")
                        .HasForeignKey("DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildServer", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("ServerLinks")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.StfcServer", "StfcServer")
                        .WithMany()
                        .HasForeignKey("StfcServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("StfcServer");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildSettings", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithOne()
                        .HasForeignKey("HoshiBot.Domain.Entities.GuildSettings", "GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.GuildVeilGroup", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("VeilGroupLinks")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.StfcVeilGroup", "StfcVeilGroup")
                        .WithMany()
                        .HasForeignKey("StfcVeilGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");

                    b.Navigation("StfcVeilGroup");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.IncursionsRegionDefault", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcRegion", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.NotificationRole", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("NotificationRoles")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.PendingModalInput", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.RoeViolationReport", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.ShieldReminder", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcSystem", "StfcSystem")
                        .WithMany()
                        .HasForeignKey("StfcSystemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HoshiBot.Domain.Entities.GuildMember", "GuildMember")
                        .WithMany()
                        .HasForeignKey("GuildId", "DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMember");

                    b.Navigation("StfcSystem");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.ShieldReminderNotification", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.ShieldReminder", "ShieldReminder")
                        .WithMany("Notifications")
                        .HasForeignKey("ShieldReminderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShieldReminder");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcAlliance", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcServer", "Server")
                        .WithMany("Alliances")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcAllianceDiplomacy", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcAlliance", "SourceAlliance")
                        .WithMany()
                        .HasForeignKey("SourceAllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.StfcAlliance", "TargetAlliance")
                        .WithMany()
                        .HasForeignKey("TargetAllianceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SourceAlliance");

                    b.Navigation("TargetAlliance");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcAllianceDiscordInvite", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcAlliance", "Alliance")
                        .WithMany("DiscordInvites")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alliance");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcAllianceNameHistory", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcAlliance", "StfcAlliance")
                        .WithMany("NameHistory")
                        .HasForeignKey("StfcAllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StfcAlliance");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcEventDateConfirmation", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcNewsPost", "StfcNewsPost")
                        .WithMany("Confirmations")
                        .HasForeignKey("StfcNewsPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StfcNewsPost");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcEventStatus", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcRegion", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Region");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcNewsPostGuildMessage", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcNewsPost", "StfcNewsPost")
                        .WithMany("GuildMessages")
                        .HasForeignKey("StfcNewsPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StfcNewsPost");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcPlayer", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcAlliance", "Alliance")
                        .WithMany("Players")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HoshiBot.Domain.Entities.StfcServer", "Server")
                        .WithMany("Players")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alliance");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcPlayerNameHistory", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcPlayer", "StfcPlayer")
                        .WithMany("NameHistory")
                        .HasForeignKey("StfcPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StfcPlayer");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcServer", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcRegion", "Region")
                        .WithMany("Servers")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.StfcVeilGroup", "VeilGroup")
                        .WithMany("Servers")
                        .HasForeignKey("VeilGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Region");

                    b.Navigation("VeilGroup");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcServerDiscordInvite", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcServer", "Server")
                        .WithMany("DiscordInvites")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Server");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcServerStatus", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcServer", "StfcServer")
                        .WithOne()
                        .HasForeignKey("HoshiBot.Domain.Entities.StfcServerStatus", "StfcServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StfcServer");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcSystem", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcTerritory", "Territory")
                        .WithMany("Systems")
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcTerritoryNeighbour", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcTerritory", "NeighbourTerritory")
                        .WithMany()
                        .HasForeignKey("NeighbourTerritoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.StfcTerritory", "Territory")
                        .WithMany()
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NeighbourTerritory");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcTerritoryOwnership", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcAlliance", "Alliance")
                        .WithMany("TerritoryOwnerships")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.StfcServer", "Server")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.StfcTerritory", "Territory")
                        .WithMany("Ownerships")
                        .HasForeignKey("TerritoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alliance");

                    b.Navigation("Server");

                    b.Navigation("Territory");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcVeilGroup", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcRegion", "Region")
                        .WithMany("VeilGroups")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcVeilGroupDiscordInvite", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.StfcVeilGroup", "VeilGroup")
                        .WithMany("DiscordInvites")
                        .HasForeignKey("VeilGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VeilGroup");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.ThreadRemovalRequest", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany("ThreadRemovalRequests")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordGuild", "Guild")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.UserPlayer", b =>
                {
                    b.HasOne("HoshiBot.Domain.Entities.DiscordUser", "User")
                        .WithMany("PlayerLinks")
                        .HasForeignKey("DiscordUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiBot.Domain.Entities.StfcPlayer", "StfcPlayer")
                        .WithMany("UserLinks")
                        .HasForeignKey("StfcPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StfcPlayer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.Alert", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.Announcement", b =>
                {
                    b.Navigation("ReadReceipts");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.DiscordGuild", b =>
                {
                    b.Navigation("AdminRoles");

                    b.Navigation("AllianceLinks");

                    b.Navigation("ChannelPermissionExpectations");

                    b.Navigation("Members");

                    b.Navigation("NotificationRoles");

                    b.Navigation("ServerLinks");

                    b.Navigation("ThreadRemovalRequests");

                    b.Navigation("VeilGroupLinks");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.DiscordUser", b =>
                {
                    b.Navigation("GuildMemberships");

                    b.Navigation("PlayerLinks");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.ShieldReminder", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcAlliance", b =>
                {
                    b.Navigation("DiscordInvites");

                    b.Navigation("NameHistory");

                    b.Navigation("Players");

                    b.Navigation("TerritoryOwnerships");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcNewsPost", b =>
                {
                    b.Navigation("Confirmations");

                    b.Navigation("GuildMessages");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcPlayer", b =>
                {
                    b.Navigation("NameHistory");

                    b.Navigation("UserLinks");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcRegion", b =>
                {
                    b.Navigation("Servers");

                    b.Navigation("VeilGroups");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcServer", b =>
                {
                    b.Navigation("Alliances");

                    b.Navigation("DiscordInvites");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcTerritory", b =>
                {
                    b.Navigation("Ownerships");

                    b.Navigation("Systems");
                });

            modelBuilder.Entity("HoshiBot.Domain.Entities.StfcVeilGroup", b =>
                {
                    b.Navigation("DiscordInvites");

                    b.Navigation("Servers");
                });
#pragma warning restore 612, 618
        }
    }
}
