using System.Text;
using HoshiBot.StfcCatalogSync;

var inputDir = args.Length > 0 ? args[0] : "data";
if (!Directory.Exists(inputDir))
{
    Console.Error.WriteLine($"Input directory not found: {inputDir}");
    Console.Error.WriteLine("Run this tool from the repo root (hoshi-bot-dotnet/), or pass the input directory as an argument.");
    return 1;
}

var htmlFiles = Directory.GetFiles(inputDir, "*.htm")
    .Concat(Directory.GetFiles(inputDir, "*.html"))
    .OrderBy(f => f, StringComparer.Ordinal)
    .ToList();

if (htmlFiles.Count == 0)
{
    Console.Error.WriteLine($"No .htm/.html files found in {inputDir}");
    return 1;
}

// Deduplicated by Number, which is globally unique across every server in the source data
// (unlike Name, which can repeat across veil groups — e.g. "Tanagra" exists in both EU-4
// and APAC-6 as two different servers with two different numbers).
var byNumber = new Dictionary<int, ParsedServerCard>();

foreach (var file in htmlFiles)
{
    Console.WriteLine($"Parsing {Path.GetFileName(file)}...");
    var html = await File.ReadAllTextAsync(file);

    foreach (var card in StfcCatalogHtmlParser.Parse(html))
    {
        byNumber[card.Number] = card;
    }
}

var ordered = byNumber.Values
    .OrderBy(c => c.Region, StringComparer.Ordinal)
    .ThenBy(c => c.VeilGroupCode, StringComparer.Ordinal)
    .ThenBy(c => c.Number)
    .ToList();

var regionCount = ordered.Select(c => c.Region).Distinct().Count();
var veilGroupCount = ordered.Select(c => c.VeilGroupCode).Where(v => v is not null).Distinct().Count();
var unassignedCount = ordered.Count(c => c.VeilGroupCode is null);

Console.WriteLine();
Console.WriteLine(
    $"Regions: {regionCount}, Veil groups: {veilGroupCount}, " +
    $"Servers: {ordered.Count} ({unassignedCount} without a veil group)");

var outputPath = Path.Combine("src", "HoshiBot.Data", "Seeding", "StfcCatalogSeedData.cs");
Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
await File.WriteAllTextAsync(outputPath, GenerateSourceFile(ordered));

Console.WriteLine($"Wrote {outputPath}");

return 0;

static string GenerateSourceFile(List<ParsedServerCard> entries)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("// Generated by tools/HoshiBot.StfcCatalogSync from data/*.htm — do not edit by hand.");
    sb.AppendLine("// Regenerate: dotnet run --project tools/HoshiBot.StfcCatalogSync (from the repo root)");
    sb.AppendLine("// </auto-generated>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine("namespace HoshiBot.Data.Seeding;");
    sb.AppendLine();
    sb.AppendLine("// Baseline STFC region/veil-group/server catalog, seeded into an empty database by");
    sb.AppendLine("// SeedStfcCatalogIfEmptyAsync. A server always belongs to a region and has a globally");
    sb.AppendLine("// unique Number; VeilGroup is null for newly-launched servers not assigned to one yet.");
    sb.AppendLine("// Server Name is only unique within its veil group, not globally — e.g. real data has");
    sb.AppendLine("// a \"Tanagra\" in both EU-4 and APAC-6, as two different servers.");
    sb.AppendLine("public static class StfcCatalogSeedData");
    sb.AppendLine("{");
    sb.AppendLine("    public static readonly (string Region, int Number, string? VeilGroup, string Server, string? InviteUrl)[] Entries =");
    sb.AppendLine("    [");
    foreach (var entry in entries)
    {
        var veilGroupLiteral = entry.VeilGroupCode is null ? "null" : $"\"{Escape(entry.VeilGroupCode)}\"";
        var inviteUrlLiteral = entry.InviteUrl is null ? "null" : $"\"{Escape(entry.InviteUrl)}\"";
        sb.AppendLine($"        (\"{Escape(entry.Region)}\", {entry.Number}, {veilGroupLiteral}, \"{Escape(entry.Name)}\", {inviteUrlLiteral}),");
    }
    sb.AppendLine("    ];");
    sb.AppendLine("}");
    return sb.ToString();
}

static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
