<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\HoshiBot.Domain\HoshiBot.Domain.csproj" />
    <ProjectReference Include="..\HoshiBot.Data\HoshiBot.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AspNet.Security.OAuth.Discord" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.App.Internal.Assets" Version="10.0.9" />
    <PackageReference Include="BootstrapBlazor" Version="10.7.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="NetCord" Version="1.0.0-beta.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e25b8fc0-87af-4591-8735-8ba553e00e8f</UserSecretsId>
    <Version>2.0.0</Version>
  </PropertyGroup>

</Project>
