namespace HoshiBot.Data.Seeding;

// A one-time snapshot of server 164's alliance roster (Tag, Name), captured 2026-07-08
// from an external STFC stats site's API. Unlike StfcCatalogSeedData, this isn't
// auto-regenerated — alliance rosters change constantly (renames, disbands, server
// moves), so this is just a starting point seeded once into an empty table; ongoing
// changes are expected to go through the existing Manage > STFC Catalog > Alliances
// admin pages, not a re-run of this file.
public static class StfcAllianceSeedData
{
    public const int Server164Id = 164;

    public static readonly (string Tag, string Name)[] Server164Entries =
    [
        ("ACHE", "HORDE"),
        ("AEON", "Aeon Federation"),
        ("AKA", "2 Tone"),
        ("ALNE", "Enola Reyalp"),
        ("BAS", "The Exact"),
        ("BLA", "kiki"),
        ("BOMB", "BOMBERS"),
        ("BONK", "Legion Of Bonkers"),
        ("BPB", "Belgarion"),
        ("BRD", "Luftwaffe"),
        ("BRG", "Borg"),
        ("BURD", "Chi Burdlaz"),
        ("CN", "Centaurie"),
        ("COMM", "Atomic"),
        ("DÀRK", "DàrkSide"),
        ("DEST", "Destiny"),
        ("DFÖ", "Dt Föderation"),
        ("DSX", "Deep Space Unimatr"),
        ("EASY", "RedSith"),
        ("EIN", "ODINS ERBE Chris"),
        ("ENTS", "The smurf"),
        ("EVH", "eventHorizon"),
        ("FAE", "northgard helms"),
        ("FCU", "Fans Club Union"),
        ("FRAC", "FRAC"),
        ("GBP", "G B P"),
        ("GER", "Deutschland Squad"),
        ("GLI", "SoLaRiS"),
        ("GOT", "Ghosts of Terra"),
        ("GOTG", "Guard Galaxy"),
        ("GRW", "Groiwenwoilers"),
        ("HALO", "Halo"),
        ("HOME", "Home"),
        ("IST", "Star Warrior"),
        ("JM", "Just Me"),
        ("JOLO", "Jolo"),
        ("ĶÅØŞ", "三ĶÅØŞ一ŦĤ3ØЯŸ三"),
        ("KCDQ", "MercenairesDuChaos"),
        ("KOBY", "Kobayashi Maru"),
        ("KR", "krivbas"),
        ("KW", "KRAFTW3RK"),
        ("LF", "Lost Falcons"),
        ("LORD", "CAKE"),
        ("LR", "Lone Ranger"),
        ("LSR", "Lonesome Rider"),
        ("LWC", "Kooperative"),
        ("LZY", "Lazy"),
        ("MMM", "MMMM"),
        ("MON", "flop"),
        ("MSM", "MainStreaM"),
        ("NATO", "Allied forces"),
        ("NGEN", "New Generation"),
        ("NX", "NX01"),
        ("ODA", "centra spike"),
        ("ONE", "Oneeeee"),
        ("PAR", "Parked"),
        ("PLN", "Polonium"),
        ("POL", "POZNAN"),
        ("REM", "REMUS"),
        ("RESP", "Molieres82"),
        ("RETR", "RETRIEVING"),
        ("RIF", "We Are the Borg"),
        ("ROCK", "OurShipsPlayRocK"),
        ("RUHE", "Sternenflotte"),
        ("SD", "sdfgh"),
        ("SG", "StarGate"),
        ("SHQL", "SHADØW BASE"),
        ("SL", "S0l0"),
        ("SOC", "Commonwealth"),
        ("ST", "Starfighters"),
        ("STA", "Star Trek1"),
        ("STS", "stsfi"),
        ("SЗI", "Section 31"),
        ("T", "power"),
        ("THOR", "Asgard"),
        ("TLE", "The Lost Empire"),
        ("TOS", "TheOrionSyndicate"),
        ("TTT", "stoned alliance"),
        ("USF", "USS Freedom"),
        ("VDM", "Les bambous"),
        ("VOY", "uss voyager"),
        ("XF", "XtremeFighters"),
        ("ZAT", "terra prime"),
        ("ВСТК", "Команда Гагарина"),
    ];
}
