using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HoshiBot.Data.Seeding;

// Baseline STFC region/veil-group/server catalog, seeded into an empty database by
// SeedStfcCatalogIfEmptyAsync. A server always belongs to a region and has a globally unique
// Number; VeilGroup is null for newly-launched servers not assigned to one yet. Server Name is
// only unique within its veil group, not globally — e.g. real data has a "Tanagra" in both
// EU-4 and APAC-6, as two different servers.
//
// Sourced from two embedded JSON resources in the server-overview page's own raw shape,
// regenerated by tools/HoshiBot.StfcSeedSync from data/servers.htm: the server records and a
// parallel array of Discord-invite records joined here on the server number. This loader
// projects the fields the seeder uses.
public static class StfcCatalogSeedData
{
    private record ServerRecord(
        [property: JsonPropertyName("serverid")] int ServerId,
        [property: JsonPropertyName("name")] string Name,
        [property: JsonPropertyName("region")] string Region,
        [property: JsonPropertyName("groupname")] string? GroupName);

    private record InviteRecord(
        [property: JsonPropertyName("serverId")] int ServerId,
        [property: JsonPropertyName("discordUrl")] string? DiscordUrl);

    public static readonly (string Region, int Number, string? VeilGroup, string Server, string? InviteUrl)[] Entries = Load();

    private static (string Region, int Number, string? VeilGroup, string Server, string? InviteUrl)[] Load()
    {
        var servers = LoadResource<ServerRecord[]>("HoshiBot.Data.Seeding.StfcServerSeedData.json");
        var invites = LoadResource<InviteRecord[]>("HoshiBot.Data.Seeding.StfcServerInviteSeedData.json");

        var inviteByServer = new Dictionary<int, string>();
        foreach (var invite in invites)
            if (!string.IsNullOrEmpty(invite.DiscordUrl))
                inviteByServer[invite.ServerId] = invite.DiscordUrl;

        return servers
            .Select(s => (s.Region, s.ServerId, s.GroupName, s.Name,
                inviteByServer.TryGetValue(s.ServerId, out var url) ? url : null))
            .ToArray();
    }

    private static T LoadResource<T>(string resourceName)
    {
        var assembly = Assembly.GetExecutingAssembly();
        using var stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{resourceName}' not found.");

        return JsonSerializer.Deserialize<T>(stream)
            ?? throw new InvalidOperationException($"Embedded resource '{resourceName}' deserialized to null.");
    }
}
