using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace HoshiBot.Data.Seeding;

// A one-time snapshot of every server's up/down/maintenance state, captured from an external
// STFC stats site's server-status feed. Stored as an embedded JSON resource in the feed's own
// raw shape (regenerated by tools/HoshiBot.StfcSeedSync from data/server-status.json), so a
// refresh is just dropping a fresh feed in and re-running the tool. This loader projects the
// three fields the seeder uses; the feed's other fields (name, region, transfer state, …) are
// ignored. Seeded once into an empty table as a baseline for StfcServerStatus (see there for
// why this is temporary rather than an ongoing sync).
public static class StfcServerStatusSeedData
{
    private record Entry(
        [property: JsonPropertyName("id")] int Id,
        [property: JsonPropertyName("status")] int Status,
        [property: JsonPropertyName("maintenance")] string Maintenance);

    public static readonly (int StfcServerId, int Status, string Maintenance)[] Entries = Load();

    private static (int StfcServerId, int Status, string Maintenance)[] Load()
    {
        var assembly = Assembly.GetExecutingAssembly();
        const string resourceName = "HoshiBot.Data.Seeding.StfcServerStatusSeedData.json";
        using var stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException($"Embedded resource '{resourceName}' not found.");

        var entries = JsonSerializer.Deserialize<Entry[]>(stream)
            ?? throw new InvalidOperationException($"Embedded resource '{resourceName}' deserialized to null.");

        return entries.Select(e => (e.Id, e.Status, e.Maintenance)).ToArray();
    }
}
